### PR TITLE
Code Review algorithm v2 - Issue #89

### PR DESCRIPTION
**Pull request by ewjmulder**
Code review -  Issue #89
The algorithm looks good to me. I just changed some names and added a few semi-colons. Of course you can decide for yourself if and how much you want to include. I think naming is important for reading and understanding the code, so I updated a few names that I think could be clearer.
Some things to consider:
- Is there always enough entropy generated to get a password of the configured length and the pseudo random indices?
- What if the configured password length is less than the number of subsets configured (so for example password length 3 with all subsets checked). Not really a useful configuration, but this will currently crash the algorithm I guess.
- You might want to include some randomness in a unit test to verify if characters from the configured subsets are always present in the generated password. A fixed unit test will never cover any new ground of course. See for example: https://github.com/jsverify/jsverify But it's also a matter of taste if you (dis)like randomness in a unit test.

### CODE REVIEW

**Comment by guillaumevincent** [comment]
Thank you, I will merge and update the tests

**Comment by ewjmulder** [comment]
Ok, great. Sorry for not fixing all test issues due to the renaming.

**Comment by ewjmulder** [comment]
Actually I see there is an error regarding my code duplication prevention change. I will fix that first.

**Comment by guillaumevincent** [comment]
I will push the fixed version with your modifications

**Comment by guillaumevincent** [comment]
I've merge your pull request by hand
Thanks

**Comment by ewjmulder** [comment]
I thought, I'll quickly do the review by editing the source files directly in Github. But then you can only commit one file at a time. So the list of 'fix' commits is pretty long and messy, sorry for that. I recommend you do a 'squash' PR merge (see: https://github.com/blog/2141-squash-your-commits) and just keep one comment 'Code review algorithm v2', so you loose the 'fix' commit stuff.

**Comment by ewjmulder** [comment]
"I've merge your pull request by hand"
-> Ok, probably better indeed :)

**Comment by guillaumevincent** [comment]
yes, I can keep your modification:

https://github.com/lesspass/core/commits/master

Better to see contributors at the end
Thank you

**Comment by ewjmulder** [comment]
Ok, keeping contributors is nice indeed, thanks!
Let me know if you like some more feedback later on (then I will do a proper checkout + local building+testing ;).

**Comment by guillaumevincent** [comment]
I reuse numbers and counter to avoid to many work for every API using the service.

> Is there always enough entropy generated to get a password of the configured length and the pseudo random indices?

Don't know how to calculate "enough entropy". Enough compare to what ?

> What if the configured password length is less than the number of subsets configured (so for example password length 3 with all subsets checked). Not really a useful configuration, but this will currently crash the algorithm I guess.

Interface should limit password length to 4.

I will add some random tests in the future. Thanks

**Comment by ewjmulder** [comment]
> I rollback numbers and counter variables to avoid to many work for every API using the service.
Ok, I understand

> Don't know how to calculate "enough entropy". Enough compare to what ?
What I mean is you start with a big number and keep doing long divisions to get the next 'random' character or index. At some point that big number has been 'used up' by the divisions. I also do not know how to calculate if it's big enough to provide all the entropy (division steps) you need, but it was just something that crossed my mind. So for instance if I ask for a password of the max length and all subsets, will the generated entropy number be divided all the way till nothing is left or is it always big enough to provide the amount of divisions you need? Maybe you can do some educated guess.

**Comment by guillaumevincent** [comment]
I calculated max length equal to 35. After you don't have enough entropy and get only `a` char (index = 0).

    max_length = math.floor(math.log(int('dc33d431bce2b01182c613382483ccdb0e2f66482cbba5e9d07dab34acc7eb1e', 16))/math.log(26 + 26 + 10 + 32)) - 4

**Comment by ewjmulder** [comment]
That's what I meant indeed. 35 seems like a pretty high number. Still you might consider raising it even more by getting a bigger hash or maybe 2 concatenated hashes with different (predefined) inputs. Some (slightly paranoid) users might prefer even longer passwords.

**Comment by guillaumevincent** [comment]
I will update the keylen of pdkdf2 up to 64 bytes.
With this option we can create a password with a max length equal to 74.
IMO that will be good

**Comment by ewjmulder** [comment]
Agreed, sounds like enough to keep v2 relevant for a long time!

**Comment by guillaumevincent** [comment]
arf webcrypto doesn't works with 64 bytes.

`AES key length must be 128 or 256 bits`

**Comment by guillaumevincent** [comment]
We will stay with 32 bytes for now

**Comment by ewjmulder** [comment]
Argh, annoying.
But 35 is still acceptable.

**Pull request closed without merging**
